Origin/feature/no ref/button componet
alizaenazet/gamedoc-android pull request #16
Opened 2024-01-02 06:49 UTC by LouisSetyandaru

2024-01-02 19:40 UTC, alizaenazet commented
component mu ada error, pastikan ga ada error saat pull request

<img width="874" alt="Screenshot 2024-01-03 at 02 39 53" src="https://github.com/alizaenazet/gamedoc-android/assets/96227680/71a94806-93e7-4a9e-8042-50775ba8baf7">

2024-01-02 19:42 UTC, alizaenazet requested changes
buat previewnya tidak error biar aku bisa bantu cek udah bener atau tidak. masalah e ini yang kamu pull request branch e error.

2024-01-02 19:53 UTC, LouisSetyandaru commented
> buat previewnya tidak error biar aku bisa bantu cek udah bener atau tidak. masalah e ini yang kamu pull request branch e error.

iki aku nggak ero cara buat button dropdown, iku kode tekan gpt meke error nggak ero opo o, trs lak aku ndelok ndek yutub iku pake file XML lah iku aku nggak ero cara gawene, XML iku dapet tekan endi

2024-01-02 19:57 UTC, alizaenazet commented
> > buat previewnya tidak error biar aku bisa bantu cek udah bener atau tidak. masalah e ini yang kamu pull request branch e error.
> 
> iki aku nggak ero cara buat button dropdown, iku kode tekan gpt meke error nggak ero opo o, trs lak aku ndelok ndek yutub iku pake file XML lah iku aku nggak ero cara gawene, XML iku dapet tekan endi

oooh okay. kamu bisa coba bikin issue terkait problem mu itu dan taro digroup line sapa tau laine bisa bantu termasuk mentor kita dan bakal ketemu jalan keluar.

2024-01-02 19:59 UTC, LouisSetyandaru commented
> > > buat previewnya tidak error biar aku bisa bantu cek udah bener atau tidak. masalah e ini yang kamu pull request branch e error.
> > 
> > 
> > iki aku nggak ero cara buat button dropdown, iku kode tekan gpt meke error nggak ero opo o, trs lak aku ndelok ndek yutub iku pake file XML lah iku aku nggak ero cara gawene, XML iku dapet tekan endi
> 
> oooh okay. kamu bisa coba bikin issue terkait problem mu itu dan taro digroup line sapa tau laine bisa bantu termasuk mentor kita dan bakal ketemu jalan keluar.

woke

2024-01-07 08:51 UTC, alizaenazet requested changes
overall dah bener semua tinggal hapus commented code

2024-01-07 08:51 UTC, alizaenazet commented on app/src/main/java/com/example/gamedoc/ui/components/Button.kt
> +//                        color = Secondary,
minta tolong sekalian ini dihapus semua ya kalo emang nda kepake, panjang banget soalnya

2024-01-07 09:09 UTC, alizaenazet approved these changes
nice

2024-01-07 09:09 UTC, merged